name: docker-compose-actions-workflow
on: push
jobs:
    api-tests:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   uses: actions/cache@v2
                name: Cache composer files
                with:
                    path: ~/.composer
                    key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                    restore-keys: |
                        ${{ runner.os }}-composer-
            -   name: Change composer cache owner
                run: |
                    sudo chown -R 1000:1000 ~/.composer
                    sudo chown -R 1000:1000 ..
            -   name: setup
                run: make setup
            -   name: Test
                run: make tests
